import { Salon, Offer } from './types';

export const CITIES = ['Mumbai', 'Bangalore', 'Delhi', 'Pune'];

export const LOCALITIES_BY_CITY: Record<string, string[]> = {
  Mumbai: ['Bandra', 'Colaba', 'Andheri West', 'Juhu'],
  Bangalore: ['Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield'],
  Delhi: ['Karol Bagh', 'Connaught Place', 'South Ext', 'Rajouri Garden'],
  Pune: ['Koregaon Park', 'Kalyani Nagar', 'Kothrud', 'Aundh'],
};

export const OFFERS: Offer[] = [
  {
    code: 'GLOWFIRST',
    discount: 20,
    type: 'percentage',
    description: 'Get 20% OFF on your first booking with any salon!',
    expiry: '2026-12-31',
    minBookingValue: 499,
  },
  {
    code: 'SPALUXE',
    discount: 500,
    type: 'flat',
    description: 'Flat ₹500 discount on Luxury Spa & Facial packages.',
    expiry: '2026-08-31',
    minBookingValue: 1999,
  },
  {
    code: 'HAIRMAGIC',
    discount: 15,
    type: 'percentage',
    description: '15% off on Hair highlights and creative haircut styling.',
    expiry: '2026-09-30',
    minBookingValue: 799,
  },
];

export const SALONS: Salon[] = [
  {
    id: 'salon-1',
    name: 'Prism Hair & Nail Studio',
    city: 'Mumbai',
    locality: 'Bandra',
    pincode: '400050',
    rating: 4.8,
    reviewsCount: 312,
    gender: 'unisex',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    description: 'Prism Hair & Nail Studio is bandra’s premier high-concept salon. We specialize in precision hair color, modern balayage, creative haircuts, and custom luxury nail art designed by award-winning specialists.',
    address: 'Shop 4, Hill Road, Opposite Starbucks, Bandra West, Mumbai, MH - 400050',
    distance: '1.2 km',
    coordinates: { lat: 19.0544, lng: 72.8402 },
    openingHours: '09:00 AM - 09:00 PM',
    contact: '+91 98765 43210',
    services: [
      {
        id: 's-101',
        name: 'Creative Haircut & Blow Dry',
        category: 'haircut',
        price: 999,
        duration: '45 mins',
        description: 'Personalized hairstyle tailored to your face shape, followed by professional blow dry.',
      },
      {
        id: 's-102',
        name: 'Balayage & Global Hair Color',
        category: 'haircut',
        price: 4499,
        duration: '150 mins',
        description: 'Seamless French hand-painted highlights tailored to give natural depth and movement.',
      },
      {
        id: 's-103',
        name: 'Luxury Chrome Gel Extensions',
        category: 'nail_art',
        price: 1799,
        duration: '75 mins',
        description: 'Premium gel extensions with chrome overlay or custom hand-painted nail designs.',
      },
      {
        id: 's-104',
        name: 'Moisture Lock Hair Spa',
        category: 'spa',
        price: 1499,
        duration: '60 mins',
        description: 'Revitalizing deep-conditioning treatment to restore hair shine and strength.',
      },
    ],
    stylists: [
      {
        id: 'st-101',
        name: 'Vikram Malhotra',
        role: 'Master Creative Hair Director',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        specialties: ['French Balayage', 'Pixie Cuts', 'Shags'],
      },
      {
        id: 'st-102',
        name: 'Carlos Santana',
        role: 'Senior Nail Artist',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        specialties: ['3D Acrylic Art', 'Chrome Extensions', 'Nail Jewels'],
      },
    ],
    beforeAfter: [
      {
        id: 'ba-101',
        before: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1605497746444-11d59451d4bd?auto=format&fit=crop&w=400&q=80',
        description: 'Golden Blonde French Balayage on dry, curly hair.',
      },
      {
        id: 'ba-102',
        before: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c9?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
        description: 'Sleek Short Bob Transition from damaged hair split-ends.',
      },
    ],
    reviews: [
      {
        id: 'r-101',
        userName: 'Priya Sen',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
        rating: 5,
        date: '2026-06-12',
        comment: 'Vikram Malhotra is a hair magician! I got the French Balayage and it looks incredibly natural and vibrant. The salon is beautifully clean and hygienic.',
        service: 'Balayage & Global Hair Color',
        photos: ['https://images.unsplash.com/photo-1605497746444-11d59451d4bd?auto=format&fit=crop&w=150&q=80'],
      },
      {
        id: 'r-102',
        userName: 'Rishi Kapoor',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
        rating: 4,
        date: '2026-05-28',
        comment: 'Great service. I had a hair spa and a standard crop haircut. Booking online was effortless.',
        service: 'Creative Haircut & Blow Dry',
      },
    ],
  },
  {
    id: 'salon-2',
    name: 'Glow & Co. Luxury Wellness Spa',
    city: 'Bangalore',
    locality: 'Indiranagar',
    pincode: '560038',
    rating: 4.9,
    reviewsCount: 450,
    gender: 'unisex',
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=800&q=80',
    description: 'Experience deep tranquility and skin rejuvenation. Glow & Co offers world-class Ayurvedic massages, hydrating European facials, medical-grade peels, and therapeutic reflexology in an oasis of peace.',
    address: '1024, 100 Feet Road, Beside Infinitea, Indiranagar, Bangalore, KA - 560038',
    distance: '0.8 km',
    coordinates: { lat: 12.9719, lng: 77.6412 },
    openingHours: '08:00 AM - 10:00 PM',
    contact: '+91 87654 32109',
    services: [
      {
        id: 's-201',
        name: 'Signature HydroPeel Hydrafacial',
        category: 'skincare',
        price: 2499,
        duration: '75 mins',
        description: 'Multi-step facial skin treatment to cleanse, exfoliate, extract, and infuse rich serums.',
      },
      {
        id: 's-202',
        name: 'Swedish Deep Tissue Therapy',
        category: 'spa',
        price: 1999,
        duration: '90 mins',
        description: 'Full-body deep muscle pressure massage to relieve tension and increase energy.',
      },
      {
        id: 's-203',
        name: 'Rose Clay Glow Ritual',
        category: 'skincare',
        price: 1799,
        duration: '60 mins',
        description: 'Nourishing botanical scrub followed by organic pink clay body or facial wrap.',
      },
    ],
    stylists: [
      {
        id: 'st-201',
        name: 'Elena Gilbert',
        role: 'Chief Medical Esthetician',
        rating: 5.0,
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
        specialties: ['Hydrafacials', 'Chemical Peels', 'Anti-aging Treatments'],
      },
      {
        id: 'st-202',
        name: 'Devendra Gowda',
        role: 'Senior Ayurvedic Therapist',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
        specialties: ['Deep Tissue Massage', 'Abhyanga Massage', 'Shirodhara'],
      },
    ],
    beforeAfter: [
      {
        id: 'ba-201',
        before: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
        description: 'Skincare facial treatment: Deep pore cleansing and acne reduction results.',
      },
    ],
    reviews: [
      {
        id: 'r-201',
        userName: 'Shalini Murthy',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        rating: 5,
        date: '2026-06-21',
        comment: 'Absolutely stunning! The Hydrafacial by Elena did magic to my dull dry skin. The calming music and aroma oils make this the perfect weekend recharge spot.',
        service: 'Signature HydroPeel Hydrafacial',
        photos: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=150&q=80'],
      },
    ],
  },
  {
    id: 'salon-3',
    name: 'Radiant Brides Luxury Salon',
    city: 'Delhi',
    locality: 'Karol Bagh',
    pincode: '110005',
    rating: 4.7,
    reviewsCount: 280,
    gender: 'female',
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80',
    description: 'Delhi’s ultimate destination for premium bridal styling. Over a decade of crafting magical bridal makeovers, heavy North Indian wedding makeup, cocktail looks, and organic skin prep regimens.',
    address: 'Block-3A, Pusa Road, Opp Metro Pillar 122, Karol Bagh, New Delhi, DL - 110005',
    distance: '2.5 km',
    coordinates: { lat: 28.6448, lng: 77.1912 },
    openingHours: '10:00 AM - 08:30 PM',
    contact: '+91 76543 21098',
    services: [
      {
        id: 's-301',
        name: 'Premium HD Bridal Makeup',
        category: 'bridal_makeup',
        price: 14999,
        duration: '180 mins',
        description: 'High-definition airbrush bridal makeup, luxury lash accents, hair bun drape, and saree draping.',
      },
      {
        id: 's-302',
        name: 'Cocktail/Sangeet Makeup & Hair',
        category: 'bridal_makeup',
        price: 5999,
        duration: '120 mins',
        description: 'Glamorous, dew-focused makeup paired with modern Hollywood curls or messy drapes.',
      },
      {
        id: 's-303',
        name: 'Bridal Skin Glow Prep & Gold Facial',
        category: 'skincare',
        price: 3499,
        duration: '90 mins',
        description: 'Gold-infused glow facial coupled with intense face oxygenation and neck polishing.',
      },
    ],
    stylists: [
      {
        id: 'st-301',
        name: 'Aisha Sharma',
        role: 'Celebrity Bridal & HD Airbrush Stylist',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
        specialties: ['Airbrush Makeup', 'Traditional Bridal Bun', 'Heavy Saree Draping'],
      },
    ],
    beforeAfter: [
      {
        id: 'ba-301',
        before: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=400&q=80',
        description: 'Traditional heavy North Indian Bridal makeup transformation.',
      },
    ],
    reviews: [
      {
        id: 'r-301',
        userName: 'Megha Gupta',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
        rating: 5,
        date: '2026-06-15',
        comment: 'Aisha designed my bridal makeup, and I felt like a queen! It stayed flawless all night long despite the summer Delhi heat. Highly recommend their prep sessions.',
        service: 'Premium HD Bridal Makeup',
      },
    ],
  },
  {
    id: 'salon-4',
    name: 'The Velvet Lounge Salon',
    city: 'Pune',
    locality: 'Koregaon Park',
    pincode: '411001',
    rating: 4.6,
    reviewsCount: 195,
    gender: 'unisex',
    image: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=800&q=80',
    description: 'The Velvet Lounge is a chic aesthetic boutique. Best known for creative undercut trims, therapeutic scalp spa massages, luxury pedicure lounges, and bright pop nail art colors that spark conversation.',
    address: 'Lane 7, Opposite Sunderban Hotel, Koregaon Park, Pune, MH - 411001',
    distance: '0.4 km',
    coordinates: { lat: 18.5362, lng: 73.8940 },
    openingHours: '10:00 AM - 09:30 PM',
    contact: '+91 65432 10987',
    services: [
      {
        id: 's-401',
        name: 'Creative Haircut & Styling',
        category: 'haircut',
        price: 799,
        duration: '40 mins',
        description: 'Modern trends haircut from classic fades to shags, includes relaxing head wash.',
      },
      {
        id: 's-402',
        name: 'Aromatic Foot Massage Spa',
        category: 'spa',
        price: 1199,
        duration: '50 mins',
        description: 'Soothing foot soak with magnesium salts, organic oils massage, and hot towel wrap.',
      },
      {
        id: 's-403',
        name: 'Matte & Gloss Nail Art Combo',
        category: 'nail_art',
        price: 1299,
        duration: '60 mins',
        description: 'Gel paint design with dual finish options and rhinestone enhancements.',
      },
    ],
    stylists: [
      {
        id: 'st-401',
        name: 'Rajesh Kumar',
        role: 'Master Barber & Unisex Hairstylist',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        specialties: ['Fade Cuts', 'Mullets', 'Scalp Rejuvenation Massage'],
      },
    ],
    beforeAfter: [
      {
        id: 'ba-401',
        before: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=400&q=80',
        description: 'High skin fade undercut and pompadour style.',
      },
    ],
    reviews: [
      {
        id: 'r-401',
        userName: 'Aniket Deshmukh',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
        rating: 4,
        date: '2026-06-05',
        comment: 'Rajesh gave me a perfect high fade haircut. Really nice ambience and modern chairs.',
        service: 'Creative Haircut & Styling',
      },
    ],
  },
  {
    id: 'salon-5',
    name: 'Urban Edge Barber & Spa',
    city: 'Mumbai',
    locality: 'Colaba',
    pincode: '400001',
    rating: 4.7,
    reviewsCount: 164,
    gender: 'male',
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    description: 'A dedicated masculine grooming center. Urban Edge blends old-school hot towel wet shaves with modern charcoal deep-cleansing facials and expert beard styling in an upscale gentlemanly lodge.',
    address: 'Shop 12, Regal Cinema Building, Colaba Causeway, Mumbai, MH - 400001',
    distance: '3.1 km',
    coordinates: { lat: 18.9224, lng: 72.8318 },
    openingHours: '09:00 AM - 10:00 PM',
    contact: '+91 54321 09876',
    services: [
      {
        id: 's-501',
        name: 'The Royal Beard Trim & Razor Shave',
        category: 'haircut',
        price: 599,
        duration: '40 mins',
        description: 'Premium beard styling, straight razor neck line cleanup, and cooling oil application.',
      },
      {
        id: 's-502',
        name: 'Scalp Detox & Haircut Combo',
        category: 'haircut',
        price: 999,
        duration: '60 mins',
        description: 'Tea tree shampoo wash, anti-dandruff scalp scrub massage, and custom beard-cut combo.',
      },
      {
        id: 's-503',
        name: 'Men Charcoal Deep Exfoliating Spa',
        category: 'spa',
        price: 1199,
        duration: '50 mins',
        description: 'Charcoal black mask peel, ozone steam pore extraction, and cold stone facial massage.',
      },
    ],
    stylists: [
      {
        id: 'st-501',
        name: 'Karan Mehra',
        role: 'Senior Barber',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
        specialties: ['Straight Razor Shaves', 'Beard Shaping', 'Pompadours'],
      },
    ],
    beforeAfter: [
      {
        id: 'ba-501',
        before: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c9?auto=format&fit=crop&w=400&q=80',
        after: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=400&q=80',
        description: 'Gentleman Trim & Classic Beard line shape transition.',
      },
    ],
    reviews: [
      {
        id: 'r-501',
        userName: 'Aditya Roy',
        userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
        rating: 5,
        date: '2026-06-19',
        comment: 'Karan Mehra is incredible. His razor alignment is a work of art. The hot towel wet shave is highly addictive!',
        service: 'The Royal Beard Trim & Razor Shave',
      },
    ],
  },
];
